import random  # Usado para escolher mensagens aleatórias
from datetime import datetime  # Pode ser usado para personalizar mensagens com base na data/hora

# Dicionário que agrupa mensagens sustentáveis por tema,
# cada chave é um tema e o valor é uma lista de mensagens relacionadas
mensagens_por_tema = {
    "Mobilidade Sustentável": [
        "Vá de bicicleta e descubra liberdade ecológica! 🚲",
        "Compartilhar caronas aproxima pessoas e preserva recursos! 🚗",
        "Caminhar para destinos próximos é saúde e leveza! 🚶‍♀️",
        "Transporte público reduz emissões e trânsito! 🚌",
        "Plante árvores no trajeto e ajude o verde urbano! 🌳",
        "Capacete e bicicleta mostram segurança e sustentabilidade! 🛡️",
        "Use bicicletários comunitários e fortaleça o bairro! 🚲",
        "Planeje deslocamentos para reduzir uso de carro! 🔁",
        "Patinetes elétricos oferecem deslocamento divertido e limpo! 🛴",
        "Mapear rotas verdes ajuda você e a natureza! 🗺️",
        "Pedalar é respirar ar puro intensamente! 🚴",
        "Evitar trânsito reduz estresse e poluição! 🚦",
        "Apoie transporte limpo e eficiente! 🚌",
        "Carona reversa é compartilhar e economizar! 🤝",
        "Troque táxi por bike em pequenas distâncias! 🚲",
        "Pneus calibrados economizam combustível e dinheiro! 🛞",
        "Andar é reencontrar seu próprio ritmo! 👣",
        "Rotas compartilhadas fortalecem a comunidade! 👥",
        "Pedalar cura mente, corpo e planeta! 💚",
        "Transporte consciente transforma cidades! 🌍",
        "Ciclovias seguras conectam e protegem! 🛣️",
        "Trem é conforto com pouco impacto ambiental! 🚆",
        "Chegar sem trânsito é chegar com paz! 🕊️",
        "Dirigir suave economiza combustível e estresse! ⛽",
        "Carros elétricos aproximam-nos do futuro! 🔌",
        "Pedalar hoje planta o amanhã que desejamos! 🌱",
        "Mobilidade limpa é estilo de vida sustentável! 🌟",
        "Sentir o trajeto sem carro traz liberdade! 🚶",
        "Transporte verde é escolha de cidadania! 🌿",
        "Cada trajeto consciente soma ao planeta! 🌍"
    ],
    "Plantio e Reflorestamento": [
        "Plante uma árvore por mês e renove a vida! 🌳",
        "Cultivar raízes fortalece o solo e sua conexão! 🌱",
        "Cuidar de sementes é manter a esperança viva! 🌼",
        "Árvores urbanas oferecem sombra e paz para todos! 🏙️",
        "Compartilhar sementes multiplica a esperança! 🌾",
        "Refloreste, renove e reestabeleça conexão com a Terra! 🔄",
        "Cada muda é um sopro de esperança! 🌿",
        "Prefira plantas nativas e valorize a biodiversidade! 🌸",
        "Solo saudável nasce de cuidado e respeito! 🧑‍🌾",
        "Hortas verticais otimizam espaço e nutrem! 🪴",
        "Preservar raízes mantém cultura e ecossistemas! 🌾",
        "Reutilizar garrafas PET para plantas é vida do lixo! ♻️",
        "Flores nativas atraem polinizadores essenciais! 🐝",
        "Pequenos quintais podem virar florestas urbanas! 🌇",
        "Plantar com crianças é plantar futuros! 🍃",
        "Adote uma árvore para lembrar da nossa relação com a natureza! 🌳",
        "Celebre o crescimento com fotos e carinho! 📷",
        "Cuide dos brotos com paciência e atenção! 🌱",
        "A sombra de uma árvore é vida para quem vem atrás! ☀️",
        "Plantar é um ato de celebração da vida! 🎉",
        "Mutirões de plantio ecoam união e esperança! 🤝",
        "Frutíferas oferecem alimento e afeto! 🍎",
        "Reflorestar áreas degradadas é reescrever histórias! 📖",
        "Reflorestamento é colher o futuro no presente! 🌍",
        "Folhas caídas viram adubo que nutre o solo! 🍂",
        "Plante provisões, plante memórias! 🌱",
        "Regar no fim da tarde preserva água e nutre cedo! 🌅",
        "Compartilhe seu verde e inspire outros! 📢",
        "Cada galho merece cuidado e atenção! 🌿",
        "A mata cresce no chão que você rega com cuidado! 💚"
    ],
    "Proteção da Fauna": [
        "Respeite os animais em seu habitat natural! 🐾",
        "Não compre produtos de origem cruel! 🚫",
        "Adote com responsabilidade e acolha com amor! ❤️",
        "Prefira plantas a pesticidas tóxicos e proteja a fauna! 🌿",
        "Feche frestas em casa para evitar atropelamentos! 🦎",
        "Comedouros atraem pássaros e trazem alegria! 🐦",
        "Preserve os rios para que os peixes possam nadar livres! 🐟",
        "Evite produtos com óleo de palma — muitos animais sofrem! 🥥",
        "Apoie ações de resgate e proteção animal! 🤗",
        "Não alimente animais com lixo — evite doenças! 🍽️",
        "Preservar habitats é garantir a vida selvagem! 🏞️",
        "Observe animais sem perturbar — seja um visitante respeitoso! 👀",
        "Recicle para proteger os lares da fauna! 🗑️",
        "Limpar praias pode salvar a vida marinha! 🏖️",
        "Denunciar maus-tratos é atitude corajosa! 📣",
        "Evite áreas de caça — apoie a preservação das espécies! 🐾",
        "Refloreste para reabrir caminhos da fauna! 🌱",
        "Participe de resgates voluntários locais! 🙋‍♀️",
        "Crie espaços seguros na sua casa para os animais urbanos! 🏡",
        "Apoie ONGs: elas protegem quem não pode falar! 🏥",
        "Mostrar amor pela fauna é mostrar amor pela Terra! 🐾",
        "Dizer não à caça de peles preserva vidas e culturas! 🚫",
        "Proteger barreiras naturais fortalece ecossistemas! 🌳",
        "Compostagem evita químicos tóxicos no solo dos animais! 🍂",
        "Dirija com cuidado onde há fauna — vidas estão na estrada! 🚗",
        "Casas sem perigo = fauna urbana segura! 🏠",
        "Apoie campanhas de resgate e recuperação! 📢",
        "Amor animal é compromisso com o equilíbrio! ❤️",
        "Reduzir pesticidas protege quem depende da natureza! 🥕",
        "Cada vida animal é peça valiosa do planeta! 🌍"
    ],
    "Economia de Água": [
        "Cada gota economizada hoje é chance de vida amanhã! 💧",
        "Fechar a torneira ao escovar preserva muitos rios! 🦷",
        "Banho de 5 minutos pode ser relaxante e sustentável! 🚿",
        "Reutilizar água da máquina é cuidar da casa e do planeta! 🧺",
        "Regar plantas ao amanhecer evita desperdício e fortalece a natureza! 🌱",
        "Água da chuva é presente gratuito — use com sabedoria! 🌧️",
        "Um cano pingando pode desperdiçar litros por dia — conserte o vazamento! 🔧",
        "Lavar o carro com balde economiza até 300 litros! 🪣",
        "Solo saudável absorve melhor a água — plante mais verde! 🌿",
        "Água é vida — trate com carinho! 💙",
        "Fechar a torneira ao lavar louça é amor ao planeta! 🍽️",
        "Água limpa não nasce do nada — preserve nascentes! 🏞️",
        "Cada gota tem valor — não desperdice! 💧",
        "Pequenas mudanças salvam milhões de litros por ano! 🔄",
        "Água desperdiçada não volta do mesmo jeito — cuide dela! 🚰",
        "Um mundo mais verde começa com menos desperdício! 🌍",
        "Recolher água da chuva para limpar demonstra consciência! 🧽",
        "Ensinar crianças a economizar é educar para o futuro! 👧",
        "Jardins sustentáveis consomem menos e equilibram a natureza! 🌼",
        "Cada descarga consciente preserva milhares de litros por ano! 🚽",
        "Evitar mangueira evita desperdício e mostra cuidado! 🚫",
        "A água que economizamos é vital amanhã! ⏳",
        "Ducha econômica é conforto e respeito ao planeta! 🚿",
        "Reaproveite água da pia para lavar quintais! 🧼",
        "Uma torneira bem fechada simboliza responsabilidade! 🚱",
        "Cuide da água como o tesouro que ela é! 💎",
        "Levar a família a economizar transforma lares! 🏠",
        "Filtro limpo e torneira segura garantem bom uso! 🧴",
        "O amanhã depende do que economizamos hoje! 📅",
        "Água conecta todos os seres vivos — preserve com amor! 🌐"
    ],
    "Economia de Energia": [
        "Apagar luzes é acender consciência ambiental! 💡",
        "Desligar aparelhos da tomada reduz consumo e conta! 🔌",
        "Aproveitar luz natural é viver em harmonia e economia! 🌞",
        "Banhos curtos com água morna são relaxantes e sustentáveis! 🚿",
        "Substituir lâmpadas por LED é escolha inteligente! 💡",
        "Evitar abrir a geladeira frequentemente preserva energia! 🧊",
        "Passar roupas de uma vez economiza tempo e luz! 👕",
        "Desligar a TV da tomada evita consumo invisível! 📺",
        "Ar-condicionado só quando realmente necessário! ❄️",
        "Painéis solares trazem futuro renovável para casa! ☀️",
        "Casa ventilada consome menos e respira melhor! 🌬️",
        "Cozinhar com tampa economiza gás e energia! 🍲",
        "Use micro-ondas só quando necessário! 🍽️",
        "Lavar roupas à noite evita picos de energia! 🧺",
        "Geladeira cheia consome menos — organize-se! 🧃",
        "Computador em standby também consome — desligue! 💻",
        "Carregar celular além do necessário é desperdício! 📱",
        "Ventiladores gastam menos que ar-condicionado! 🌬️",
        "Equipamentos Procel consomem menos e duram mais! 🟢",
        "Planejar o uso evita picos de consumo! 📅",
        "Descongelar freezer economiza energia! ❄️",
        "Ensine crianças a economizar energia em casa! 👨‍👩‍👧‍👦",
        "Apague luzes em ambientes vazios! 💡",
        "Instale sensores de presença e reduza desperdício! 🚶",
        "Energia limpa começa com escolhas conscientes! 🏠",
        "Desconectar o carregador evita consumo invisível! 🔌",
        "Reduzir brilho da TV protege olhos e conta! 📺",
        "Banhos solares aquecem lar e coração do planeta! 🌞",
        "Evite aparelhos de alto consumo no pico! ⏰",
        "Energia poupada hoje transforma o amanhã! 🌍"
    ],
    "Alimentação Sustentável": [
        "Prefira produtos locais e fortaleça sua comunidade! 🥕",
        "Reduzir o consumo de carne preserva nossos recursos! 🥩",
        "Cultivar uma hortinha conecta você à terra! 🌿",
        "Apoiar produtores familiares valoriza o alimento e o campo! 🚜",
        "Aproveite talos e cascas na cozinha — menos desperdício! 🍠",
        "Hortas caseiras trazem sabor e cuidado pessoal! 🌱",
        "Comer consciente é respeito ao planeta e seu corpo! 🍽️",
        "Dieta com menos carne faz bem a você e à Terra! 🌱",
        "Prefira produtos orgânicos para valorizar o solo! 🫐",
        "Plantar seu alimento nutre corpo e alma! 🪴",
        "Menos ultraprocessados é mais saúde e natureza! 🚫",
        "Cada garfada pode salvar uma árvore! 🌳",
        "Panelas tampadas economizam gás e preservam nutrientes! 🍲",
        "Compras a granel reduzem desperdício e embalagens! 🛍️",
        "Compartilhar receitas multiplica boas práticas! 🥗",
        "Slow food é resistência à pressa prejudicial! 🕰️",
        "Refeições conscientes aproximam a família! 🍛",
        "Menos desperdício significa mais sabor e alegria! 😊",
        "Compostar restos transforma lixo em vida! 🌱",
        "Preservar sementes é garantir futuro agrícola! 🌾",
        "Vegetais maduros são pratos nutritivos! 🥦",
        "Refeição consciente é ato de amor ao planeta! ❤️",
        "Chá caseiro traz sabor, economia e paz! 🍵",
        "Comida de verdade sustenta corpos e florestas! 🌱",
        "Proteínas vegetais são escolhas leves para o mundo! 🌿",
        "Aproveitar talos como caldo aproveita tudo! 🥣",
        "Pratos coloridos são sinônimo de sustentabilidade! 🎨",
        "Cozinhar consciente é cuidar de todos nós! 🌍",
        "Plantar temperos é cultivar responsabilidade! 🌿",
        "Preparar alimentos com consciência alimenta o futuro! 🍳"
    ],
        "Sustentabilidade": [
        "Pequenas escolhas diárias constroem um futuro mais verde! ♻️",
        "Economize energia e acenda uma nova consciência! 💡",
        "Leve sua ecobag e o planeta vai agradecer! 🛍️",
        "Cinco minutos a menos no banho salvam água! 🚿",
        "Cultivar plantas em casa é plantar esperança! 🌳",
        "Você pode ajudar a resfriar o planeta com atitudes! 🌡️",
        "Diga sim a um mundo com menos lixo! 📦",
        "Alimentar a Terra com amor é comer conscientemente! 🍽️",
        "Pedalar faz bem ao corpo, à alma e ao planeta! 🚲",
        "Produtos naturais cuidam de você e do meio ambiente! 🧼",
        "Transforme o velho em algo novo com criatividade! ✂️",
        "Lixo no lixo, consciência no coração! 🗑️",
        "Dê vida nova aos objetos e resista ao descarte! 🛠️",
        "Compras conscientes são atos de amor ao planeta! 🛒",
        "Aproveite a luz do sol antes de acender lâmpadas! 🌤️",
        "Separar o lixo é separar vida de destruição! 🚮",
        "Garrafas filtradas evitam toneladas de plástico! 🚰",
        "Conhecimento em sustentabilidade floresce em atitudes! 📚",
        "Doar é dar nova chance a pessoas e objetos! 👚",
        "Os 5 R’s do futuro sustentável começam com você! ✋",
        "Comida local e orgânica fortalece solo e comunidade! 🥗",
        "Proteger a natureza é proteger a si mesmo! 🏞️",
        "Viver com menos é ganhar liberdade e consciência! 🎈",
        "Menos consumo, mais propósito para a Terra! 📦",
        "Trocar e consertar é um ato de amor ecológico! 🔧",
        "Ambiente limpo reflete mente limpa! 🧹",
        "Seus hábitos hoje são legado verde amanhã! 🍀",
        "Compartilhe sua voz pela sustentabilidade! 📣",
        "A bússola para o futuro aponta para consumo consciente! 🧭",
        "Cada conversa ambiental é semente de mudança! 💬"
    ],
    "Reciclagem": [
        "O que parece lixo pode ser vida nova! ♻️",
        "Jogar fora não existe — você escolhe o destino! 🚯",
        "Caixas e garrafas recicladas viram magia! 🧃",
        "Separar lixo organiza sua casa e mente! 🧠",
        "Reciclar é dar um fôlego ao planeta! 🔄",
        "Menos lixo, menos poluição no ar! 🏭",
        "Uma sacola para reciclável já faz diferença! 🛍️",
        "Plástico, papel e vidro certos são recicláveis! 🔍",
        "Reciclar é arte — transforme o velho em novo! 🎨",
        "Reciclar alivia sua pegada ecológica! 👣",
        "Pesquise antes de jogar — conhecimento é poder! 📲",
        "Reciclar gera empregos e dignidade! 🤝",
        "Seu lixo reciclado impacta muitas vidas! 🌐",
        "Reciclagem começa dentro de casa! 🏠",
        "Recicle como se não houvesse outro planeta! 🌎",
        "Vidro reciclado pode voltar a ser vidro! 🍾",
        "Papéis reciclados salvam florestas inteiras! 📝",
        "Tetra Pak reciclado vira futuro! 🧡",
        "Sacolas plásticas podem ter novas vidas! 🛍️",
        "Embalagens limpas mostram respeito aos recicladores! 🧼",
        "Ensinar reciclagem é ensinar cuidado! 📚",
        "Uma lata reciclada ilumina horas! 💡",
        "Compartilhe ideias sustentáveis com amigos! 📣",
        "Papel reciclado é presente com propósito! 🎁",
        "Crianças que reciclam ensinam o mundo! 👧",
        "Reciclar é pensar soluções criativas! 🧠",
        "Planta esperança em tempos de urgência climática! 🌼",
        "Seu gesto pode salvar toneladas de lixo! 🕊️",
        "Respeite heróis recicladores! 🧤",
        "Reciclar é um alvo simples para mudança! 🎯"
    ],

    "Educação Ambiental": [
        "Compartilhe conhecimentos sobre reciclagem com sua rede! 📚",
        "Ler sobre ecologia planta ideias transformadoras! 📖",
        "Participar de mutirões fortalece a comunidade e o planeta! 🧹",
        "Documentários sobre natureza inspiram ações reais! 🎥",
        "Ensinar crianças a cuidar do meio ambiente faz o futuro! 👧",
        "Apoie causas ambientais para fortalecer mudanças! 🤝",
        "Faça pequenas palestras e motive sua comunidade! 🎤",
        "Divulgar práticas sustentáveis nas redes multiplica chances! 📣",
        "Visitar áreas verdes educa e renova a alma! 🏞️",
        "Organize grupos para estudar sobre mudanças climáticas! 🧠",
        "Conhecer a biodiversidade local fortalece o senso de pertencimento! 🐾",
        "Acompanhe eventos sustentáveis da região e participe! 📅",
        "Debates sobre meio ambiente são sementes de transformação! 💬",
        "Doar livros verdes espalha conhecimento e cuidado! 🎁",
        "Use educação como ferramenta de mudança! ✏️",
        "Inspirar é semear consciência ambiental em outros! 🌱",
        "Educação verde resgata valores e atitudes! 🌿",
        "Incentivar plantio em escolas multiplica afeto pelo planeta! 🌼",
        "Aprender com povos originários é valorizar tradição e natureza! 🌾",
        "Produzir conteúdo sobre meio ambiente renova debates! 🎧",
        "Redes engajadas em sustentabilidade mobilizam mentes! 🌐",
        "Conhecimento sobre clima fortalece ações individuais! 🌡️",
        "Ensinar sobre consumo consciente forma cidadãos mais responsáveis! 🛍️",
        "Saber é plantar sementes para um amanhã melhor! 🌍",
        "Conhecer o ciclo da água transforma atitudes diárias! 💧",
        "Estudar biodiversidade fortalece a conexão com a vida! 🐝",
        "Informação é a raiz de práticas mais sustentáveis! 🌱",
        "Compartilhar conteúdo ambiental amplia o impacto! 📲",
        "Ações educativas são planos de mudança concreta! 🗓️",
        "Educação ambiental é legado sustentável para o futuro! 🌳"
    ],
    "Economia Circular": [
        "Reveja, reaproveite e recicle — o ciclo que cuida do planeta! 🔄",
        "Doe objetos para prolongar suas histórias! 🎁",
        "Restaure móveis para evitar consumismo excessivo! 🛠️",
        "Troque em brechós e valorize compartilhamento! 👗",
        "Compartilhar ferramentas fortalece vizinhança! 🧰",
        "Vidro e metal reciclados viram produtos novos! 🔩",
        "Arte com materiais usados revela o potencial criativo! 🎨",
        "Compre produtos remanufaturados e reduza descarte! ♻️",
        "Transforme restos em ideias sustentáveis! 💡",
        "Economia circular é verbo em ação, não teoria! 📝",
        "Do lixo ao luxo com criatividade e eco! ✂️",
        "Compostagem fecha o ciclo de vida dos resíduos! 🍂",
        "Compartilhe ferramentas para reduzir gastos e lixo! 🧰",
        "Papel reciclado possui história e identidade! 📄",
        "Venda objetos usados para dar novas vidas! 💰",
        "Economia circular é escolha de futuro consciente! 🌍",
        "Reutilizar presenteia o planeta com menos lixo! 🎁",
        "Bancos de troca fortalecem vínculos comunitários! 🤝",
        "Caixas viram organizadores — ideia reciclável! 📦",
        "Restos podem virar arte, móveis ou chapelaria! 🧵",
        "Sustentabilidade é ciclo, não linha reta! 🔁",
        "Compartilhar evita consumismo e promove união! 👯",
        "Projetos com material usado ensinam criatividade! 🎓",
        "Reaproveitar até o final é postura sustentável! 🌱",
        "Economia circular reduz produção e poluição! ⚙️",
        "Vestir roupas usadas é estilo + atitude! 👕",
        "Compartilhe livros após ler — conhecimento circular! 📚",
        "Remanufaturados economizam recursos naturais! 🛠️",
        "Economia circular é futuro em movimento! 🌐",
        "Somos todos nós no ciclo da sustentabilidade! 🌍"
    ],
    "Sustentabilidade no Lar": [
        "Compostar restos de comida transforma lixo em vida! 🍂",
        "Doe óleo de cozinha usado para reciclagem! 🛢️",
        "Tenha sua própria hortinha orgânica em casa! 🌿",
        "Use panos reutilizáveis no lugar de papel toalha! 🧼",
        "Limpeza natural com vinagre e bicarbonato é ecológica! 🧴",
        "Móveis de materiais renováveis respeitam o meio ambiente! 🪵",
        "Decoração com plantas melhora o ar e o astral! 🌵",
        "Reutilizar potes evita consumo desnecessário! 🧃",
        "Prefira tapetes e cortinas de fibras naturais! 🧶",
        "Ventile a casa para evitar ar-condicionado! 🌬️",
        "Faça produtos de limpeza caseiros e evite químicos! 🏡",
        "Organize um bazar comunitário para reutilização! 👕",
        "Use tintas ecológicas para renovar seu lar! 🎨",
        "Feche frestas para conservar energia e calor! 🧱",
        "Use baldes para capturar água do banho! 🪣",
        "Iluminação eficiente economiza energia em casa! 💡",
        "Doe o que não usa para reduzir acúmulo! 🎁",
        "Reutilize papel como rascunho antes de descartar! 📝",
        "Digitalize documentos para evitar desperdício! 📂",
        "Decore com galhos secados para charme sustentável! 🌿",
        "Prefira carpetes sustentáveis de fibras naturais! 🐑",
        "Armazenar comida em potes reaproveitáveis é inteligente! 🍱",
        "Use sensores de presença em banheiros e corredores! 🚶",
        "Capte água da chuva para limpeza e rega! 🌧️",
        "Reutilizar móveis com pintura dá nova cara ao lar! 🖌️",
        "Reserve um espaço para reciclagem doméstica! 🗑️",
        "Use ervas aromáticas como assinatura olfativa da casa! 🌿",
        "Fazer sapatos de juta é artesanato com alma! 👟",
        "Dias sem luz podem ser momentos de conexão e reflexão! 🕯️",
        "Um lar consciente irradia sustentabilidade para a vizinhança! 🏠"
    ],
    "Consumo Consciente": [
        "Compre só o que realmente precisa! 🛍️",
        "Prefira marcas que praticam sustentabilidade! 🌿",
        "Reflita antes de adicionar ao carrinho! 🧠",
        "Reutilize antes de comprar algo novo! ♻️",
        "Escolha produtos com embalagens responsáveis! 📦",
        "Doe o que não usa e transforme vidas! 👕",
        "Evite acumular — consuma com propósito! 🎯",
        "Cada compra é voto pelo planeta! 🗳️",
        "Compartilhe peças com amigos para gastar menos! 🤝",
        "Transparência da marca é sinal de compromisso! 🕵️‍♂️",
        "Prefira qualidade, não quantidade! 🏆",
        "Produtos reparáveis duram mais e causam menos impacto! 🔧",
        "Apoie produtores locais sempre que possível! 🥕",
        "Vestir eco é vestir futuro! 🌍",
        "Reflita sobre a origem dos produtos antes de comprar! 🛒",
        "Evite modismos rápidos — escolha consciência. 🔄",
        "Consumo consciente começa com autoconsciência! 🧭",
        "Compartilhar ferramentas é eco de solidariedade! 🧰",
        "Coautor do consumo consciente que você quer ver no mundo! ✍️",
        "Reutilizar dá história e significado aos objetos! 📚",
        "Pesquise selos verdes antes de comprar! ✅",
        "Menos é mais — atitude minimalista faz bem ao mundo! 🌱",
        "Trocas entre amigos evitam descartes desnecessários! 🔁",
        "Empoderar-se no consumo exige reflexão! 🧠",
        "Escolhas sustentáveis geram menos lixo! 🗑️",
        "Consumo consciente é ato de autocuidado! ❤️",
        "Repensar o consumo é resgatar o valor das coisas! 💎",
        "Compras online conscientes exigem pesquisa! 🖥️",
        "Materiais duráveis reduzem o consumo infantil! 👶",
        "Cada compra sustentável é um passo rumo ao futuro! 🚶‍♂️"
    ]
    
}
temas_semanais = [
    "Água",
    "Consumo Consciente",
    "Energia",
    "Reciclagem",
    "Mobilidade Sustentável",
    "Alimentação Saudável",
    "Biodiversidade",
    "Lixo Eletrônico"
]
mensagens_por_tema = {
    "Água": [
        "Feche a torneira ao escovar os dentes!",
        "Reaproveite a água da máquina de lavar.",
        "Evite banhos longos. Cada minuto conta!"
    ],
    "Consumo Consciente": [
        "Compre apenas o necessário.",
        "Prefira produtos com menos embalagens.",
        "Doe o que não usa mais."
    ],
    "Energia": [
        "Desligue aparelhos da tomada ao sair.",
        "Aproveite a luz natural durante o dia.",
        "Troque lâmpadas por versões de LED."
    ],
    # Adicione mais mensagens para os outros temas...
}
def obter_tema_semana():
    semana_do_ano = datetime.now().isocalendar()[1]
    index = (semana_do_ano - 1) % len(temas_semanais)
    return temas_semanais[index]
def obter_tema_semana():
    semana_do_ano = datetime.now().isocalendar()[1]
    index = (semana_do_ano - 1) % len(temas_semanais)
    return temas_semanais[index]
def gerar_mensagem(nome):
    tema = obter_tema_semana()
    mensagens = mensagens_por_tema.get(tema, ["Cuide do planeta!"])
    mensagem = random.choice(mensagens)
    return f"{nome}, {mensagem}", tema
mensagens_condicionais = {
    'segunda-feira': ["Comece a semana com consciência ambiental!"],
    'sexta-feira': ["Sextou! Hora de pensar no planeta!"],
    'domingo': ["Domingo é dia de recarregar e cuidar da Terra!"]
}

def gerar_mensagem(nome):
    hoje = datetime.today().strftime('%A').lower()  # Pega o dia da semana atual

    mensagens_validas = []

    # Sorteia um tema e adiciona suas mensagens
    if mensagens_por_tema:
        tema = random.choice(list(mensagens_por_tema.keys()))
        mensagens_validas.extend(mensagens_por_tema[tema])
    else:
        tema = None

    # Adiciona mensagens específicas do dia da semana, se existirem
    if hoje in mensagens_condicionais:
        mensagens_validas.extend(mensagens_condicionais[hoje])

    # Se não houver mensagens, retorna aviso
    if not mensagens_validas:
        return "Nenhuma mensagem disponível no momento.", None

    # Escolhe uma mensagem aleatória
    mensagem = random.choice(mensagens_validas)

    # Personaliza a mensagem com o nome do usuário (se houver)
    if nome:
        mensagem = f"{mensagem} 🌱 {nome.capitalize()}, você faz a diferença!"

    return mensagem, tema
